apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngrok
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngrok
  template:
    metadata:
      labels:
        app: ngrok
    spec:
      containers:
      - name: ngrok
        image: wernight/ngrok@sha256:db041ea2c4de7f0dd4b9bdc47d286c6e5fa4488468708ba249e9de75ca7fdd29
        imagePullPolicy: IfNotPresent
        args:
        - ngrok
        - http
        - http://flightdeck-ingressgateway.flightdeck.svc.cluster.local
        ports:
        - name: api
          containerPort: 4040
        readinessProbe:
          httpGet:
            path: /api
            port: api
---
apiVersion: v1
kind: Service
metadata:
  name: ngrok
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: ngrok
  ports:
  - targetPort: api
    name: api
    protocol: TCP
    port: 4040
