prometheus:
  spec:
    additionalScrapeConfigs:
    - job_name: 'kube-prometheus-stack'
      scrape_interval: 10s
      honor_labels: true
      metrics_path: '/federate'
      params:
        'match[]':
          - '{__name__=~"(app|deploy|external|hpa|istio|namespace_cpu|namespace_memory|svc):.*"}'
      static_configs:
      - targets:
        - 'kube-prometheus-stack-prometheus.kube-prometheus-stack.svc:9090'
        - 'flightdeck-prometheus.kube-prometheus-stack.svc:9090'
