version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
    - |
      git clone https://github.com/asdf-vm/asdf.git "$HOME/.asdf" --branch v0.8.1
    - . "$HOME/.asdf/asdf.sh"
    - asdf version
    - asdf plugin add argocd
    - asdf plugin add helm
    - asdf plugin add kubectl
    - asdf plugin add terraform
    - asdf plugin add terraform-docs
    - asdf plugin add tflint
    - asdf install
  build:
    commands:
    - echo "$SSH_KEY" > id_rsa
    - export SSH_IDENTITY_FILE="$PWD/id_rsa"
    - chmod 600 id_rsa
    - export GIT_SSH_COMMAND="ssh -F none -o IdentitiesOnly=yes -i $SSH_IDENTITY_FILE"
    - make

cache:
  paths:
  - /root/.tflint.d/**/*
