name: istio-component-monitor
additionalLabels:
  monitoring: istio-components
  release: istio
jobLabel: istio
targetLabels: [app]
selector:
  matchExpressions:
  - {key: istio, operator: In, values: [pilot]}
namespaceSelector:
  any: true
endpoints:
- port: http-monitoring
  interval: 15s
