{{- if .Values.prometheus.spec.additionalScrapeConfigs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "prometheus.fullname" . }}-scrape-config
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
data:
  additional-scrape-configs.yaml: {{ toYaml .Values.prometheus.spec.additionalScrapeConfigs | b64enc | quote }}
{{- end }}
