apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dex.fullname" . }}
  labels:
    {{- include "dex.labels" . | nindent 4 }}
data:
  config.yaml: |
    issuer: https://{{ .Values.issuer.host }}{{ .Values.issuer.path }}

    storage:
      type: kubernetes
      config:
        inCluster: true

    web:
      http: 0.0.0.0:{{ .Values.service.port }}

    oauth2:
      responseTypes: [ "code", "token", "id_token" ]
      skipApprovalScreen: true

    {{- with .Values.config.staticClients }}
    staticClients:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.config.connectors }}
    connectors:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.config.staticPasswords }}
    staticPasswords:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    enablePasswordDB: {{ .Values.config.enablePasswordDB }}
