apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vpa.suffixedname" (merge (dict "suffix" "admission-controller") .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vpa.labels" . | nindent 4 }}
    app.kubernetes.io/component: admissionController
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "vpa.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: admissionController
  template:
    metadata:
      labels:
        {{- include "vpa.labels" . | nindent 8 }}
        app.kubernetes.io/component: admissionController
    spec:
      containers:
      - args:
        - --client-ca-file=/etc/tls-certs/ca.crt
        - --tls-cert-file=/etc/tls-certs/tls.crt
        - --tls-private-key=/etc/tls-certs/tls.key
        - --webhook-service={{ include "vpa.suffixedname" (merge (dict "suffix" "admission-controller") .) }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: {{ .Values.admissionController.deployment.image.repository }}:{{ .Values.admissionController.deployment.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.admissionController.deployment.image.pullPolicy }}
        {{- with .Values.admissionController.deployment.imagePullSecrets }}
        imagePullSecrets:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        name: admission-controller
        ports:
        - containerPort: 8000
        - containerPort: 8944
          name: prometheus
        {{- with .Values.admissionController.deployment.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.admissionController.deployment.nodeSelector }}
        nodeSelector:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.admissionController.deployment.affinity }}
        affinity:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.admissionController.deployment.tolerations }}
        tolerations:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
        - mountPath: /etc/tls-certs
          name: tls-certs
          readOnly: true
      securityContext:
        {{- toYaml .Values.admissionController.deployment.securityContext | nindent 8 }}
      serviceAccountName: {{ include "vpa.serviceAccountName" (merge (dict "component" "admissionController") .) }}
      volumes:
      - name: tls-certs
        secret:
          secretName: {{ include "vpa.suffixedname" (merge (dict "suffix" "tls") .) }}
