{{- if .Values.admissionController.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vpa.serviceAccountName" (merge (dict "component" "admissionController") .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vpa.labels" . | nindent 4 }}
    app.kubernetes.io/component: admissionController
  {{- with .Values.admissionController.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
