apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flightdeck-ui
  namespace: {{ .Release.Namespace }}
spec:
  secretName: flightdeck-tls
  duration: 2160h
  renewBefore: 360h
  subject:
    organizations:
    - flightdeck
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
  - {{ .Values.ingress.host }}
  issuerRef:
    name: {{ .Values.certificate.issuer.name }}
    kind: {{ .Values.certificate.issuer.kind }}
