apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    flightdeck.thoughtbot.com/layer: base
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: cert-manager
  namespace: {{ .Release.Namespace }}
spec:
  destination:
    namespace: {{ .Release.Namespace }}
    server: {{ .Values.destination.server }}
  project: flightdeck
  source:
    chart: cert-manager
    helm:
      values: |
        global:
          leaderElection:
            namespace: {{ .Release.Namespace }}
        installCRDs: true
        securityContext:
          # https://github.com/jetstack/cert-manager/issues/2147
          fsGroup: 1001
        {{- with index .Values "cert-manager" "awsRoleArn" }}
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: {{ . }}
        {{- end }}
    repoURL: {{ index .Values "cert-manager" "repoURL" }}
    targetRevision: {{ index .Values "cert-manager" "version" }}
