apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    flightdeck.thoughtbot.com/layer: base
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: external-dns
  namespace: {{ .Release.Namespace }}
spec:
  destination:
    namespace: {{ .Release.Namespace }}
    server: {{ .Values.destination.server }}
  project: flightdeck
  source:
    chart: external-dns
    helm:
      values: |
        {{- with index .Values "external-dns" "awsRoleArn" }}
        serviceAccount:
          annotations:
            eks.amazonaws.com/role-arn: {{ . }}
        {{- end }}
    repoURL: {{ index .Values "external-dns" "repoURL" }}
    targetRevision: {{ index .Values "external-dns" "version" }}
