apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    flightdeck.thoughtbot.com/layer: gateways
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: istio-ingress
  namespace: {{ .Release.Namespace }}
spec:
  destination:
    namespace: {{ .Release.Namespace }}
    server: {{ .Values.destination.server }}
  project: flightdeck
  source:
    path: manifests/charts/gateways/istio-ingress
    helm:
      values: |
        gateways:
          istio-ingressgateway:
            name: flightdeck-ingressgateway
            labels:
              istio: flightdeck
        global:
          istioNamespace: {{ .Values.istio.namespace }}
    repoURL: {{ .Values.istio.repoURL }}
    targetRevision: {{ .Values.istio.version }}
