apiVersion: v1
kind: Service
metadata:
  name: glauth
  labels:
    app: glauth
spec:
  type: ClusterIP
  ports:
  - port: 3893
    targetPort: ldap
    protocol: TCP
    name: ldap
  selector:
    app: glauth
