{{- if .Values.updater.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vpa.serviceAccountName" (merge (dict "component" "updater") .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vpa.labels" . | nindent 4 }}
    app.kubernetes.io/component: updater
  {{- with .Values.updater.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
