{{- if .Values.recommender.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "vpa.serviceAccountName" (merge (dict "component" "recommender") .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vpa.labels" . | nindent 4 }}
  {{- with .Values.recommender.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
