apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "ascp.fullname" . }}
  labels:
    {{- include "ascp.labels" . | nindent 4 }}
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "ascp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.daemonset.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ascp.selectorLabels" . | nindent 8 }}
        {{- with .Values.daemonset.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.daemonset.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.daemonset.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ascp.serviceAccountName" . }}
      hostNetwork: true
      containers:
      - name: provider-aws-installer
        {{- with .Values.daemonset.podSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        image: "{{ .Values.daemonset.image.repository }}:{{ .Values.daemonset.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.daemonset.image.pullPolicy }}
        args:
        - --provider-volume=/etc/kubernetes/secrets-store-csi-providers
        resources:
          {{- toYaml .Values.daemonset.resources | nindent 10 }}
        {{- with .Values.daemonset.env }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.daemonset.envFrom }}
        envFrom:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
          - mountPath: "/etc/kubernetes/secrets-store-csi-providers"
            name: providervol
          - name: mountpoint-dir
            mountPath: /var/lib/kubelet/pods
            mountPropagation: HostToContainer
      volumes:
        - name: providervol
          hostPath:
            path: "/etc/kubernetes/secrets-store-csi-providers"
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: DirectoryOrCreate
      {{- with .Values.daemonset.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.daemonset.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.daemonset.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.daemonset.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
