apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: flightdeck
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    {{- toYaml .Values.gateway.selector | nindent 4 }}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    {{- range .Values.gateway.domains }}
    - {{ . }}
    {{- end }}
    tls:
      httpsRedirect: {{ .Values.gateway.requireTLS }}
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    {{- range .Values.gateway.domains }}
    - {{ . }}
    {{- end }}
    tls:
      mode: SIMPLE
      credentialName: flightdeck-tls
