nameOverride: ""
fullnameOverride: ""

destination:
  server: https://kubernetes.default.svc

certificate:
  create: true
  domains: []
  issuer:
    create: true
    name: flightdeck
    spec: {}

gateway:
  requireTLS: true
  selector:
    istio: flightdeck

ingress:
  host: ""
  requireTLS: true
