{{- if .Values.certificate.issuer.create -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.certificate.issuer.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
{{- end -}}
