apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: flightdeck-ui
  namespace: {{ .Release.Namespace }}
spec:
  hosts:
  - {{ .Values.ingress.host }}
  gateways:
    {{ toYaml .Values.ingress.gateways | indent 6 | trim }}
  http:
  - match:
    - uri:
        prefix: /dex
    route:
    - destination:
        host: dex
